{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: low-altitude-rest-stop
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: low-altitude-rest-stop-server
                port:
                  number: {{ .Values.server.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: low-altitude-rest-stop-admin-web
                port:
                  number: {{ .Values.adminWeb.service.port }}
{{- end }}
