import {
  faArrowLeft,
  faArrowRightFromBracket,
  faBell,
  faChartColumn,
  faChartLine,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleXmark,
  faDesktop,
  faDownload,
  faFolderOpen,
  faGaugeHigh,
  faHardDrive,
  faHouseSignal,
  faListCheck,
  faLock,
  faMagnifyingGlass,
  faMobileScreenButton,
  faPlus,
  faProjectDiagram,
  faRefresh,
  faRocket,
  faScrewdriverWrench,
  faShieldHalved,
  faSliders,
  faSwatchbook,
  faTableCellsLarge,
  faTrashCan,
  faUserCog,
  faUserShield,
  faUsers,
  faWandMagicSparkles,
} from '@fortawesome/free-solid-svg-icons'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import type { IconKey } from '@/types'

export const iconRegistry: Record<IconKey, IconDefinition> = {
  overview: faHouseSignal,
  users: faUsers,
  projects: faProjectDiagram,
  analytics: faChartLine,
  settings: faScrewdriverWrench,
  logs: faTableCellsLarge,
  dashboard: faGaugeHigh,
  command: faSwatchbook,
  directory: faUsers,
  permission: faUserShield,
  folder: faFolderOpen,
  shield: faShieldHalved,
  rocket: faRocket,
  chart: faChartColumn,
  server: faHardDrive,
  sliders: faSliders,
  lock: faLock,
  bell: faBell,
  audit: faListCheck,
  download: faDownload,
  back: faArrowLeft,
  menu: faTableCellsLarge,
  search: faMagnifyingGlass,
  refresh: faRefresh,
  plus: faPlus,
  edit: faUserCog,
  delete: faTrashCan,
  swap: faProjectDiagram,
  export: faDownload,
  spark: faWandMagicSparkles,
  success: faCircleCheck,
  warning: faCircleExclamation,
  danger: faCircleXmark,
  info: faCircleInfo,
  logout: faArrowRightFromBracket,
  mobile: faMobileScreenButton,
  desktop: faDesktop,
}
